### ISSUE TITLE
Clarification regarding manifest.yml

### ISSUE THREAD

**Issue by yackitotreeville** [william-tran/freddys-bbq#2]
Hi We are currently using PCF as PaaS. Just wondering if in manifest.yml file -sso Service - Is that a tile or User Defined Service? We are planning to purchase a tile if exists. Please guide us

**Comment by william-tran** [comment]
Sorry @yackitotreeville for the delay, I didn't have my "Watch" settings turned on in this repo. The sso service instance is an instance of Pivotal SSO. Take a look at http://docs.pivotal.io/p-identity/ for more info.
