### ISSUE TITLE
Troubleshooting SSO tile - Securing Resource Server

### ISSUE THREAD

**Issue by yackitotreeville** [william-tran/freddys-bbq#5]
Hi, We are currently using Pivotal SSO Tile.

When I secured a Resource Server: 

 `@Bean
    public ResourceServerConfigurer resourceServer(SecurityProperties securityProperties) {
        return new ResourceServerConfigurerAdapter() {

```
        @Override
        public void configure(ResourceServerSecurityConfigurer resources) {
            resources.resourceId("none");
        }

        @Override
        public void configure(HttpSecurity http) throws Exception {
            if (securityProperties.isRequireSsl()) {
                http.requiresChannel().anyRequest().requiresSecure();
            }
            http.authorizeRequests()
                .antMatchers("/api/user-profiles").hasAnyAuthority(AuthoritiesConstants.USER);
        }
    };
}`
```

I am getting following error message (this is by providing access token in the header)

`{
  "error": "access_denied",
  "error_description": "Invalid token does not contain resource id (none)"
}`

when executed uaac command line (proper {client_id} has been provided): 

`uaac curl -k {oauth_server}/clients/{client_id}
GET {{oauth_server}}/oauth/clients/{client_id}

200 OK
RESPONSE HEADERS:
  Cache-Control: no-cache, no-store, max-age=0, must-revalidate
  Content-Type: application/json;charset=UTF-8
  Date: Wed, 19 Oct 2016 19:13:16 GMT
  Expires: 0
  Pragma: no-cache
  Server: Apache-Coyote/1.1
  Strict-Transport-Security: max-age=31536000 ; includeSubDomains
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  X-Vcap-Request-Id: e944bfb6-2158-49a5-6c88-97c6e12f2b8e
  X-Xss-Protection: 1; mode=block
  Content-Length: 597
  Connection: close
RESPONSE BODY:
{
  "scope": [
    "uaa.resource",
    "openid",
    "roles",
    "user_attributes"
  ],
  "client_id": "{client_id}",
  "resource_ids": [
    "none"
  ],
  "authorized_grant_types": [
    "refresh_token",
    "authorization_code"
  ],
  "redirect_uri": [
    "https://www.getpostman.com/oauth2/callback",
    "https://rapp-profile-dev.apps.dev.gsdcf.manulife.com/api/user-profiles"
  ],
  "autoapprove": [
    "uaa.resource",
    "openid",
    "roles",
    "user_attributes"
  ],
  "action": "none",
  "authorities": [
    "uaa.resource"
  ],
  "name": "rapp-dev",
  "allowedproviders": [
    "manulife-adfs"
  ],
  "lastModified": 1476816247000,
  "type": "WEB",
  "space_guid": "2e9c7b4a-f0ba-4683-89dc-cec967bdec13"
}`

**Please guide me if I can secure resource server without providing resource_id**

**Comment by william-tran** [comment]
Tokens from UAA derive their `aud` claim from the `scope` values in the token [1]. Spring Security OAuth will only check the `aud` claim of JWT tokens if you set the resource id with 

```
        @Override
        public void configure(ResourceServerSecurityConfigurer resources) {
            resources.resourceId("none");
        }
```

Try commenting that out and see what happens. The JWT spec says that `aud` must always be checked, but because UAA derives `aud` from `scope`, if you're checking for scope values then checking the `aud` claim as well is a bit redundant. This redundancy in the relationship between `aud` and `scope` is a characteristic of UAA, other authorization servers might populate `aud` differently. 

[1] https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-Tokens.md

**Comment by yackitotreeville** [comment]
Thanks! That worked.

**Comment by yackitotreeville** [comment]
Also, I wanted to understand difference between WebSecurityConfigurerAdapter and ResourceServerConfigurerAdapter. They both seems to do similar job. Please guide me on when to use what.

**Comment by william-tran** [comment]
WebSecurityConfigurerAdapter is used for SSO applications, ResourceServerConfigurerAdapter is used for resource servers. The former is an application that requests a token for the user using the authorization code flow, the latter is an application that accepts this token in the `Authorization` header to authorize access to its API endpoints.

**Comment by yackitotreeville** [comment]
Thanks a lot. It is much more clear now.
Just one last thing - 
I have swagger for my resource services. 

Can I acheive some thing like this from my resource server

 @Override
    public void configure(WebSecurity web) throws Exception {
 web.ignoring()
            .antMatchers(HttpMethod.OPTIONS, "/**")
            .antMatchers("/swagger-ui/index.html")

**Comment by yackitotreeville** [comment]
ResourceServerConfigurerAdapter doesn't have 
method below 

@Override
public void configure(WebSecurity web) throws Exception {

}

**Comment by yackitotreeville** [comment]
Hi Will,
My apologies - I guess I haven't build it before I confirmed that it worked. 
but I get to see the error: 
{
  "error": "access_denied",
  "error_description": "Invalid token does not contain resource id (oauth2-resource)"
}

**Comment by yackitotreeville** [comment]
I am just wondering if there is a easy way to setup resourcerId using uaac

**Comment by yackitotreeville** [comment]
when I used appid for resourceId. I could able to resolve the issue. Thanks once again for the support.

**Comment by william-tran** [comment]
I'm glad you got it sorted, sorry this week has been a bit crazy.

**Comment by cnish09** [comment]
@yackitotreeville  Can you tell me how you got the appid . I am also having the same problem. I am getting the token from UAA /oauth/token using grant_type=password and passing it to the resource server. I get the same error : Invalid token does not contain resource id (appid)

**Comment by william-tran** [comment]
@cnish09 either get a scope into the token that looks like "appid.whatever", or make the app receiving the token not care about the resourceId with a:
```
new ResourceServerConfigurerAdapter() {

        @Override
        public void configure(ResourceServerSecurityConfigurer resources) {
            resources.resourceId(null);
        }
};
```
